CREATE DATABASE ConnectPlusBD;

USE ConnectPlusBD;

CREATE TABLE TipoContato(
IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR(100) NOT NULL
);

SELECT * FROM TipoContato;

CREATE TABLE Contato(
IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome NVARCHAR (100) NOT NULL,
DadosContato NVARCHAR (100) NOT NULL,
Imagem VARCHAR (255),

IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);

SELECT * FROM Contato;