CREATE DATABASE EventPlusBD;
GO

USE EventPlusBD;
GO

CREATE TABLE Instituicao(
IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
NomeFantasia NVARCHAR(100) NOT NULL,
Endereco NVARCHAR(200)NOT NULL,
CNPJ NVARCHAR(14) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoEvento(
IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE TipoUsuario(
IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE Usuario(
IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Email NVARCHAR(256) UNIQUE NOT NULL,
Nome NVARCHAR(100) NOT NULL,
Senha NVARCHAR(60) NOT NULL,

IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)
);
GO

CREATE TABLE Evento(
IdEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome NVARCHAR(100) NOT NULL,
DataEvento DATETIME NOT NULL,
Descricao TEXT NOT NULL,

IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento(IdTipoEvento),
IdInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IdInstituicao)
);
GO

CREATE TABLE Presenca(
IdPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Situacao BIT NOT NULL,

IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento)
);
GO

CREATE TABLE CometarioEvento(
IdComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
DataComentarioEvento DATETIME NOT NULL,
Nome NVARCHAR(100) NOT NULL,
Descricao NVARCHAR(200) NOT NULL,
Exibe BIT NOT NULL,

IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento)
);
GO